### ۱. لاگین (برای دریافت توکن)
POST https://localhost:7246/api/auth/login
Content-Type: application/json

{
  "username": "amir_karimi",
  "password": "Password123!"
}

### ۲. ثبت درخواست (توکن را از مرحله بالا اینجا بگذار)
POST https://localhost:7246/api/Student/submit-workflow-request
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIyN0VBMEVCMi1FQ0IwLTQ3QzQtQkVBQi01Q0YwRTdENzc2MDciLCJ1bmlxdWVfbmFtZSI6ImFtaXJfa2FyaW1pIiwiZ2l2ZW5fbmFtZSI6Itin2YXbjNixINqp2LHbjNmF24wiLCJyb2xlIjoiU3R1ZGVudCIsIlN0dWRlbnRJZCI6IjYiLCJuYmYiOjE3ODQ0MjEwNzgsImV4cCI6MTc4NDQyMTk3OCwiaWF0IjoxNzg0NDIxMDc4LCJpc3MiOiJVbml2ZXJzaXR5U3lzdGVtQVBJIiwiYXVkIjoiVW5pdmVyc2l0eVN5c3RlbUFuZ3VsYXJPclJlYWN0In0.a1299ARtcnVjVeH4LCzPn4qEGv4zuCATln8kmsd2IFo
Content-Type: application/json

{
  "templateId": 1,
  "title": "معرفی شبکه ",
  "description": "توضیحات تست"
}