# درخواست ورود برای گرفتن توکن
POST https://localhost:7246/api/auth/login
Content-Type: application/json

{
  "username": "amir_karimi",
  "password": "Password123!"
}

###

# درخواست کارنامه کل (بعد از گرفتن توکن از درخواست بالا، آن را اینجا کپی کنید)
GET https://localhost:7246/api/student/Fulltranscrip
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiJ1c2VyX3N0dWRlbnRfMDEiLCJ1bmlxdWVfbmFtZSI6IjExMTExMSIsImdpdmVuX25hbWUiOiLZhdmE24zaqdinINmG2KfbjNio24wiLCJyb2xlIjoiU3R1ZGVudCIsIlN0dWRlbnRJZCI6IjMiLCJuYmYiOjE3ODQyODUzNjEsImV4cCI6MTc4NDI4NjI2MSwiaWF0IjoxNzg0Mjg1MzYxLCJpc3MiOiJVbml2ZXJzaXR5U3lzdGVtQVBJIiwiYXVkIjoiVW5pdmVyc2l0eVN5c3RlbUFuZ3VsYXJPclJlYWN0In0.example_token_parts_here...
Accept: application/json

###
# ۴. تست متد کارنامه ترمی (GetSemesterTranscript)
GET https://localhost:7246/api/student/transcript/semester?semesterId=1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiJ1c2VyX3N0dWRlbnRfMDEiLCJ1bmlxdWVfbmFtZSI6IjExMTExMSIsImdpdmVuX25hbWUiOiLZhdmE24zaqdinINmG2KfbjNio24wiLCJyb2xlIjoiU3R1ZGVudCIsIlN0dWRlbnRJZCI6IjMiLCJuYmYiOjE3ODQyODQ5NjEsImV4cCI6MTc4NDI4NTg2MSwiaWF0IjoxNzg0Mjg0OTYxLCJpc3MiOiJVbml2ZXJzaXR5U3lzdGVtQVBJIiwiYXVkIjoiVW5pdmVyc2l0eVN5c3RlbUFuZ3VsYXJPclJlYWN0In0.9EGUW_xlJOylpt9EAkWszb2B1gjJ_2Bnr0eFbHElVJs
Accept: application/json

### ۱. ثبت درخواست جدید توسط دانشجو (اصلاح شده با قالب پویا)
POST https://localhost:7246/api/Student/submit-workflow-request?studentId=6&semesterId=1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIyN0VBMEVCMi1FQ0IwLTQ3QzQtQkVBQi01Q0YwRTdENzc2MDciLCJ1bmlxdWVfbmFtZSI6ImFtaXJfa2FyaW1pIiwiZ2l2ZW5fbmFtZSI6Itin2YXbjNixINqp2LHbjNmF24wiLCJyb2xlIjoiU3R1ZGVudCIsIlN0dWRlbnRJZCI6IjYiLCJuYmYiOjE3ODQzOTQwMTUsImV4cCI6MTc4NDM5NDkxNSwiaWF0IjoxNzg0Mzk0MDE1LCJpc3MiOiJVbml2ZXJzaXR5U3lzdGVtQVBJIiwiYXVkIjoiVW5pdmVyc2l0eVN5c3RlbUFuZ3VsYXJPclJlYWN0In0.Q1W6YfVCUgWblUUF4GkUWIdoTnraPRyYX4NVDKs8138
Content-Type: application/json

{
  "templateId": 1,
  "title": "درخواست معرفی به استاد درس انتقال داده",
  "description": "لطفاً ظرفیت درس انتقال داده را به علت پر شدن کلاس افزایش دهید."
}

### ۲. مشاهده لیست درخواست‌های ارسال شده توسط خود دانشجو
GET https://localhost:7246/api/Student/my-workflow-requests?studentId=6&semesterId=1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIyN0VBMEVCMi1FQ0IwLTQ3QzQtQkVBQi01Q0YwRTdENzc2MDciLCJ1bmlxdWVfbmFtZSI6ImFtaXJfa2FyaW1pIiwiZ2l2ZW5fbmFtZSI6Itin2YXbjNixINqp2LHbjNmF24wiLCJyb2xlIjoiU3R1ZGVudCIsIlN0dWRlbnRJZCI6IjYiLCJuYmYiOjE3ODQzOTQzNjIsImV4cCI6MTc4NDM5NTI2MiwiaWF0IjoxNzg0Mzk0MzYyLCJpc3MiOiJVbml2ZXJzaXR5U3lzdGVtQVBJIiwiYXVkIjoiVW5pdmVyc2l0eVN5c3RlbUFuZ3VsYXJPclJlYWN0In0.iPFpAjYgTZ-u13L-VDtTGr2anrOX-DPqzGilsVz7SZ4
Accept: application/json

### ۳. دریافت لیست تمام قالب‌های گردش کار فعال در سیستم (جهت انتخاب دانشجو)
GET https://localhost:7246/api/Student/workflow-templates
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIyN0VBMEVCMi1FQ0IwLTQ3QzQtQkVBQi01Q0YwRTdENzc2MDciLCJ1bmlxdWVfbmFtZSI6ImFtaXJfa2FyaW1pIiwiZ2l2ZW5fbmFtZSI6Itin2YXbjNixINqp2LHbjNmF24wiLCJyb2xlIjoiU3R1ZGVudCIsIlN0dWRlbnRJZCI6IjYiLCJuYmYiOjE3ODQzOTQ0ODQsImV4cCI6MTc4NDM5NTM4NCwiaWF0IjoxNzg0Mzk0NDg0LCJpc3MiOiJVbml2ZXJzaXR5U3lzdGVtQVBJIiwiYXVkIjoiVW5pdmVyc2l0eVN5c3RlbUFuZ3VsYXJPclJlYWN0In0.KuUgqX5i0_ie537DcFPa1eDr30mL9gKp-SO54kwdocM
Accept: application/json